site_name: DoTLMViz Docs
repo_url: https://github.com/Arktetra/DoTLMViz

theme:
  name: material

nav:
  - Home: index.md
  - decomposition:
    - PCA: decomposition/PCA.md
  - checkpointed-transformer:
    - CkptedTransformer: CkptedTransformer.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          class:
            show_source: false
          method:
            show_source: true
